### ISSUE TITLE
No module named google.probuf

### ISSUE THREAD

**Issue by joeyaa** [nitishsrivastava/deepnet#108]
hello,
when i run python setup_examples.py <path to mnist dataset> <output path>   reports the error like this:

lyy@lyy-X550JX:~/bxy/deepnet-master/deepnet/examples$ python setup_examples.py /home/lyy/bxy/mnist /home/lyy/bxy/result 
Traceback (most recent call last):
  File "setup_examples.py", line 2, in <module>
    from deepnet import util
  File "/home/lyy/bxy/deepnet-master/deepnet/util.py", line 4, in <module>
    import deepnet_pb2
  File "/home/lyy/bxy/deepnet-master/deepnet/deepnet_pb2.py", line 3, in <module>
    from google.protobuf import descriptor
ImportError: No module named google.protobuf
what is the problem?

**Comment by joeyaa** [comment]
执行conda install -c conda-forge protobuf=3.2.0
选择yes
居然成功了，原来可能还是依赖哪里没有弄好。
也问了一个博主
他说 sudo apt-get install python-protobuf
这种方案我没有试过，不过应该也可以。
