### ISSUE TITLE
I had a problem when using normalize parameter in input layer

### ISSUE THREAD

**Issue by chengyangfu** [nitishsrivastava/deepnet#11]
As title. When adding normalize: true hyperparams  in input layer, I got error. 
Does any one have the same problem ?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/local/lib/python2.7/bdb.py", line 387, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "../../trainer.py", line 1, in <module>
    from neuralnet import *
  File "../../trainer.py", line 51, in main
    model.Train()
  File "../../neuralnet.py", line 450, in Train
    self.SetUpTrainer()
  File "../../neuralnet.py", line 418, in SetUpTrainer
    self.SetUpData()
  File "../../neuralnet.py", line 408, in SetUpData
    verbose=self.verbose)
  File "../../datahandler.py", line 479, in GetDataHandles
    handlers.append(DataHandler(op, name_list, hyp_list, frac=proportions[i]))
  File "../../datahandler.py", line 616, in __init__
    self.gpu_cache.SetDataStats(i, stats_file)
  File "../../datahandler.py", line 380, in SetDataStats
    assert os.path.exists(stats_file), 'Stats file %s not found.' % stats_file
AssertionError: Stats file  not found.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

> /home/chengyangfu/deepnet/deepnet/datahandler.py(380)SetDataStats()
> -> assert os.path.exists(stats_file), 'Stats file %s not found.' % stats_file

**Comment by nitishsrivastava** [comment]
In order to use the normalize parameter, the program needs to know the data statistics (mean and variance). It looks for a file containing these stats. You can generate a stats file using deepnet/compute_data_stats.py.
