### ISSUE TITLE
question about rectified_linear

### ISSUE THREAD

**Issue by chengyangfu** [nitishsrivastava/deepnet#16]
In ff example, the rectified_linear activation function performs much better than the logistic function. Does there exist any method to pretrain the rectified_linear Neural Nets?

**Comment by nitishsrivastava** [comment]
Yes, you can use relu units in RBMs. http://www.cs.toronto.edu/~hinton/absps/reluICML.pdf

**Comment by chengyangfu** [comment]
First, I must to say the multimodal DBN example is very useful. 
Currently, I am modified this DBN and want to change the activation function from LOGISTIC to RECTIFIED LINEAR. 
The modified rectified_linear version is workable in the first layer. However, when I was training image hidden and text hidden to joint layer, the error became. 
Train Step: 0Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 387, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/chengyangfu/deepnet/deepnet/trainer.py", line 1, in <module>
    from neuralnet import *
  File "/home/chengyangfu/deepnet/deepnet/trainer.py", line 51, in main
    model.Train()
  File "/home/chengyangfu/deepnet/deepnet/neuralnet.py", line 646, in Train
    losses = self.TrainOneBatch(step)
  File "/home/chengyangfu/deepnet/deepnet/dbm.py", line 274, in TrainOneBatch
    losses2 = self.NegativePhase(step, train=True)
  File "/home/chengyangfu/deepnet/deepnet/dbm.py", line 214, in NegativePhase
    losses.append(node.GetLoss())
  File "/home/chengyangfu/deepnet/deepnet/relu_layer.py", line 46, in GetLoss
    error = self.deriv.euclid_norm()**2
AttributeError: 'NoneType' object has no attribute 'euclid_norm'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program

> /home/chengyangfu/deepnet/deepnet/relu_layer.py(46)GetLoss()
> -> error = self.deriv.euclid_norm()**2
