### ISSUE TITLE
Linear Layer error positive phase

### ISSUE THREAD

**Issue by rdevon** [nitishsrivastava/deepnet#23]
Train Step: 0Traceback (most recent call last):
  File "../../../deepnet/deepnet/trainer.py", line 56, in <module>
    main()
  File "../../../deepnet/deepnet/trainer.py", line 51, in main
    model.Train()
  File "/na/homes/dhjelm/CUDANET/deepnet/deepnet/neuralnet.py", line 646, in Train
    losses = self.TrainOneBatch(step)
  File "/na/homes/dhjelm/CUDANET/deepnet/deepnet/dbm.py", line 270, in TrainOneBatch
    losses1 = self.PositivePhase(train=True, step=step)
  File "/na/homes/dhjelm/CUDANET/deepnet/deepnet/dbm.py", line 131, in PositivePhase
    self.ComputeUp(node, train=train)
  File "/na/homes/dhjelm/CUDANET/deepnet/deepnet/dbm.py", line 108, in ComputeUp
    if layer.pos_phase:
AttributeError: 'LinearLayer' object has no attribute 'pos_phase'

**Comment by ghost** [comment]
fixed now.

**Comment by rdevon** [comment]
Hey Nitish, sorry another question.

I'm slowly digging deeper into the code.  Does l1decay need to be negative?  It appears, on the surface, to be the case, but I have no idea what "edge.temp" is at that point (and I'm worried it's a catch-all variable), but I assume (the cuds code isn't clear on this detail), that if there is a target, the sign is relative to that.  Why would I need to decay to anything but 0, and under what situations would I expect that to happen here?

thanks

-devon
