### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by rdevon** [nitishsrivastava/deepnet#28]
We haven't changed our hardware or anything related to CUDA, but we are getting errors.  What might cause this?

no CUDA-capable device is detected
Traceback (most recent call last):
  File "../../../deepnet/deepnet/trainer.py", line 56, in <module>
    main()
  File "../../../deepnet/deepnet/trainer.py", line 47, in main
    board = LockGPU()
  File "../../../deepnet/deepnet/trainer.py", line 20, in LockGPU
    cm.cuda_set_device(board)
  File "/na/homes/dhjelm/CUDANET/deepnet/cudamat/cudamat.py", line 1630, in cuda_set_device
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no CUDA-capable device is detected

**Comment by rdevon** [comment]
Ah, our bad.  Updated the kernel, but didn't reboot.  Sorry!
