### ISSUE TITLE
rbm/runall.sh execution problem 

### ISSUE THREAD

**Issue by erogol** [nitishsrivastava/deepnet#36]
I am getting this error if I run the script

Traceback (most recent call last):
  File "../../trainer.py", line 5, in <module>
    from sparse_coder import *
  File "/home/retina18/deepnet/deepnet/sparse_coder.py", line 3, in <module>
    import scipy.linalg
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/**init**.py", line 9, in <module>
    from basic import *
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/basic.py", line 14, in <module>
    from lapack import get_lapack_funcs
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/lapack.py", line 14, in <module>
    from scipy.linalg import flapack
ImportError: /usr/lib/liblapack.so.3gf: undefined symbol: ATL_chemv

Any idea why?

**Comment by erogol** [comment]
The problem is an incompatible library so removing it is the solution:

sudo apt-get remove libopenblas-base
