### ISSUE TITLE
dbn example: 'DBN' object has no attribute 'layer'

### ISSUE THREAD

**Issue by sergeyplis** [nitishsrivastava/deepnet#4]
Hi Nitish,
The rbm example works perfectly, but dbn example fails on rbm2 (after completing rbm1 training) with the following:
Traceback (most recent call last):
  File "../../trainer.py", line 56, in <module>
    main()
  File "../../trainer.py", line 51, in main
    model.Train()
  File "/deepnet/deepnet/neuralnet.py", line 497, in Train
    self.CopyModelToCPU()
  File "/deepnet/deepnet/neuralnet.py", line 340, in CopyModelToCPU
    for layer in self.layer:
AttributeError: 'DBN' object has no attribute 'layer'
## Thanks!

Sergey

**Comment by nitishsrivastava** [comment]
Added a fix in new commit.
