### ISSUE TITLE
About example of ae error 

### ISSUE THREAD

**Issue by jackiechensuper** [nitishsrivastava/deepnet#46]
Hi nitish, 
This is the error that when I ran the ae met, could you help me with that, many thanks!

Autoencoder 1
Train Step: 0Traceback (most recent call last):
  File "../../trainer.py", line 60, in <module>
    main()
  File "../../trainer.py", line 54, in main
    model.Train()
  File "/home/hchen/deepnet/deepnet/neuralnet.py", line 632, in Train
    losses = self.TrainOneBatch(step)
  File "/home/hchen/deepnet/deepnet/neuralnet.py", line 330, in TrainOneBatch
    losses2 = self.BackwardPropagate(step)
  File "/home/hchen/deepnet/deepnet/neuralnet.py", line 316, in BackwardPropagate
    loss = self.ComputeDown(node, step)
  File "/home/hchen/deepnet/deepnet/neuralnet.py", line 234, in ComputeDown
    self.UpdateLayerParams(layer, step)
  File "/home/hchen/deepnet/deepnet/neuralnet.py", line 291, in UpdateLayerParams
    layer.Update('bias', step, no_reg=True)  # By default, do not regularize bias.
  File "/home/hchen/deepnet/deepnet/parameter.py", line 84, in Update
    w = self.params[param_name]  # Parameter to be updated.
KeyError: 'bias'

**Comment by nitishsrivastava** [comment]
Fixed in latest commit. Thanks for pointing this out.

**Comment by jackiechensuper** [comment]
Dear Dr.Nitish,
I have implemented an pretrained Auto-eocoder neural network based on your
code, When I done the training, I got the trained weight and bias, but how
can I get the predictions when testing on a different new image using the
above weights?  (just one feed forward calculation and got the prediction
of final layer)
Do you have a sample example? (sorry for my naive question since there are
so many parameters and a explaining document would help a lot !)
Many thanks
Hao

**Comment by nitishsrivastava** [comment]
Take a look at https://github.com/nitishsrivastava/deepnet/blob/master/deepnet/extract_neural_net_representation.py.

**Comment by jackiechensuper** [comment]
Got it, many thanks!
