### ISSUE TITLE
still cant't run rbm/runall.sh

### ISSUE THREAD

**Issue by KerrChen** [nitishsrivastava/deepnet#72]
when I run deepnet/examples/rbm run.sh, there is an error occured. I dont't know how to fix it ,Is there anyone have the same problem? how to fix ?

~/deepnet-master/deepnet/examples/trbm$ ./runall.sh
Train Step: 0Traceback (most recent call last):
  File "../../trainer.py", line 56, in <module>
    main()
  File "../../trainer.py", line 50, in main
    model.Train()
  File "/home/diic/deepnet-master/deepnet/neuralnet.py", line 631, in Train
    self.GetTrainBatch()
  File "/home/diic/deepnet-master/deepnet/neuralnet.py", line 524, in GetTrainBatch
    self.GetBatch(self.train_data_handler)
  File "/home/diic/deepnet-master/deepnet/dbm.py", line 264, in GetBatch
    super(DBM, self).GetBatch(handler=handler)
  File "/home/diic/deepnet-master/deepnet/neuralnet.py", line 512, in GetBatch
    data_list = handler.Get()
  File "/home/diic/deepnet-master/deepnet/datahandler.py", line 627, in Get
    batch = self.gpu_cache.Get(self.batchsize, get_last_piece=self.get_last_piece)
  File "/home/diic/deepnet-master/deepnet/datahandler.py", line 396, in Get
    self.LoadData()
  File "/home/diic/deepnet-master/deepnet/datahandler.py", line 312, in LoadData
    data_cpu = self.parent.Get(self._maxpos)
  File "/home/diic/deepnet-master/deepnet/datahandler.py", line 249, in Get
    self.LoadData()
  File "/home/diic/deepnet-master/deepnet/datahandler.py", line 221, in LoadData
    self.data = self.parent.Get(self._maxpos)
  File "/home/diic/deepnet-master/deepnet/datahandler.py", line 99, in Get
    this_chunk = self.ReadDiskData(filename_list[current_file], key)
  File "/home/diic/deepnet-master/deepnet/datahandler.py", line 163, in ReadDiskData
    data = np.load(filename)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 350, in load
    return format.read_array(fid)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/format.py", line 465, in read_array
    array.shape = shape
ValueError: total size of new array must be unchanged

**Comment by jormansa** [comment]
¿Why it is calling "/home/diic/deepnet-master/deepnet/dbm.py" when you are running the RBM example?

**Comment by KerrChen** [comment]
Few days ago, I reinstalled ubuntu. Now, my system is ubuntu 12.04, CUDA 6.0,when I use ./runall.sh to run the example under deepnet/examples/ff, there is another error :
kerr@kerr-ThinkStation-D30:~/deepnet-master/deepnet/examples/ff$ ./runall.sh
Train Step: 0Traceback (most recent call last):
  File "../../trainer.py", line 58, in <module>
    main()
  File "../../trainer.py", line 52, in main
    model.Train()
  File "/home/kerr/deepnet-master/deepnet/neuralnet.py", line 631, in Train
    self.GetTrainBatch()
  File "/home/kerr/deepnet-master/deepnet/neuralnet.py", line 524, in GetTrainBatch
    self.GetBatch(self.train_data_handler)
  File "/home/kerr/deepnet-master/deepnet/neuralnet.py", line 512, in GetBatch
    data_list = handler.Get()
  File "/home/kerr/deepnet-master/deepnet/datahandler.py", line 627, in Get
    batch = self.gpu_cache.Get(self.batchsize, get_last_piece=self.get_last_piece)
  File "/home/kerr/deepnet-master/deepnet/datahandler.py", line 400, in Get
    self.ShuffleData()
  File "/home/kerr/deepnet-master/deepnet/datahandler.py", line 373, in ShuffleData
    d.swap_columns(indices1_gpu, indices2_gpu, target=d)
AttributeError: 'CUDAMatrix' object has no attribute 'swap_columns'

Sorry to have bothered you, Can you help it?

**Comment by jormansa** [comment]
what happen with CUDA 5.0 ?? Recompile the cudamat module

**Comment by KerrChen** [comment]
I recompiled cudamat, but the above error still occur.
