### ISSUE TITLE
OSError: libeigenmat.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tengshaofeng** [nitishsrivastava/deepnet#78]
hello,
when i run runall_dbn.sh,everything is ok. But when i install IDE of wingIde,and set the environment,when i run a test.py and do "from deepnet import datahandler as dh",it reports the error like this:

OSError: libeigenmat.so: cannot open shared object file: No such file or directory
File "/home/tbq/Downloads/deepnet-master/test.py", line 5, in <module>
  from deepnet import dbm
File "/home/tbq/Downloads/deepnet-master/deepnet/dbm.py", line 2, in <module>
  from neuralnet import *
File "/home/tbq/Downloads/deepnet-master/deepnet/neuralnet.py", line 8, in <module>
  from datahandler import *
File "/home/tbq/Downloads/deepnet-master/deepnet/datahandler.py", line 4, in <module>
  from choose_matrix_library import *
File "/home/tbq/Downloads/deepnet-master/deepnet/choose_matrix_library.py", line 16, in <module>
  import eigenmat as cm
File "/home/tbq/Downloads/deepnet-master/eigenmat/**init**.py", line 1, in <module>
  from eigenmat import *
File "/home/tbq/Downloads/deepnet-master/eigenmat/eigenmat.py", line 10, in <module>
  _eigenmat = ct.cdll.LoadLibrary('libeigenmat.so')
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
  return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
  self._handle = _dlopen(self._name, mode)

then i change LoadLibrary('libcudamat.so')  to LoadLibrary('/home/tbq/Downloads/deepnet-master/cudamat/libcudamat.so'),it does not works,too. i know error comes from "import cudamat".But when i import in terminal after python ,it is ok.  it does not work in wingide.
i need your help,thanks in advance

**Comment by lireagan** [comment]
same problem！！！

**Comment by ghost** [comment]
Got the same problem when I try to run the example for rbm. Here's the error:-

titan4@titan4-Precision-Tower-5810:~/deepnet/deepnet/examples/rbm$ ./runall.sh
Failed to import cudamat. Using eigenmat. No GPU will be used.
Traceback (most recent call last):
  File "../../trainer.py", line 1, in <module>
    from neuralnet import *
  File "/home/titan4/deepnet/deepnet/neuralnet.py", line 8, in <module>
    from datahandler import *
  File "/home/titan4/deepnet/deepnet/datahandler.py", line 4, in <module>
    from choose_matrix_library import *
  File "/home/titan4/deepnet/deepnet/choose_matrix_library.py", line 16, in <module>
    import eigenmat as cm
  File "/home/titan4/deepnet/eigenmat/**init**.py", line 1, in <module>
    from eigenmat import *
  File "/home/titan4/deepnet/eigenmat/eigenmat.py", line 10, in <module>
    _eigenmat = ct.cdll.LoadLibrary('libeigenmat.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: libeigenmat.so: cannot open shared object file: No such file or directory

Any help appreciated :)

**Comment by rivergold** [comment]
I also get the same error!

**Comment by a-taherkhani** [comment]
I also have the similar problem. 
I rerun the make file in the cudamat directory and reduce the gpu memory (gpu_mem) in runall_dbn.sh for the multi modal data. 
Now, it works.

**Comment by Whisht** [comment]
It happened because when use libeigenmat.so , the file is in relative path. And then the python interpreter cannot find this file if libeigenmat.so is not in current  folder.
Explaining it in a illustration:
![snipaste_2018-11-15_16-40-10](https://user-images.githubusercontent.com/16497652/48540618-891fe300-e8f5-11e8-8ae2-b1d3c4b87936.png)
