### ISSUE TITLE
[Ubuntu14.04,python2.7.5,CUDA6.5] invalid device function..cudamat.cudamat.CUDAMatException: CUDA error: no error

### ISSUE THREAD

**Issue by lireagan** [nitishsrivastava/deepnet#80]
![default](https://cloud.githubusercontent.com/assets/9458572/5514634/0063b6d0-887e-11e4-86b2-ccc9f78a90cb.png)

I got this problem, 
And I think it is not about CUDA, because I had make "NVIDIA_CUDA-6.5_Samples", and run the deviceQuery. The result is pass.
I don't know why this happens and it has trouble me for weeks.
PLEASE help me ! 
THX A LOT!

**Comment by lireagan** [comment]
I hava figure it out..
Just edit the Makefile 
![default](https://cloud.githubusercontent.com/assets/9458572/5514701/bb61d716-8881-11e4-9fbe-4e3945dc2a93.png)

**Comment by interxuxing** [comment]
Really helps! Thank you for your sharing.
If someone use cuda > 5.5, this modification of the Makefile is necessary.

**Comment by IraitzM** [comment]
Thanks for sharing! Actually I have quite the same problem but not exactly the same :) for a GTX970 I added -gencode arch=compute_52,code=sm_52 and I am still getting same error at line 640 (add_sums function) but not always :S. Every once in a while it works!

If anybody has any idea how this issue could be fixed, it would be more than appreciated :)

**Comment by YantianZha** [comment]
But I still had error, after "make" that:
![snip20160314_1](https://cloud.githubusercontent.com/assets/9017839/13761414/ae9802d6-e9f5-11e5-89ee-a3b46d96ffde.png)

My Makefile:
![snip20160314_3](https://cloud.githubusercontent.com/assets/9017839/13761420/b5f96984-e9f5-11e5-9ab9-25bcbd06896f.png)

Thanks in advance!

**Comment by guxiaoling** [comment]
@YantianZha, you may forget to add the following lines to your ~/.bashrc file (notice your cuda version)
      export CUDA_BIN=/usr/local/cuda-7.5/bin  
      export CUDA_LIB=/usr/local/cuda-7.5/lib64

**Comment by buaa-luzhi** [comment]
@IraitzM hello, Did you solve the problem,
My cuda version is 8.0,
This is my question.
Traceback (most recent call last):
  File "lstm_combo.py", line 405, in <module>
    cm.CUDAMatrix.init_random(42)
  File "/home/e829/Documents/LuZhi/20161213/unsupervised-video/cudamat/cudamat.py", line 382, in init_random
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no error

Any one can help me!
Thank you very much!

**Comment by lizhijianrd** [comment]
@buaa-luzhi Have you solved the problem? I got the similar problem with you when running ae, here are the logs:
Autoencoder 1
invalid device function
Traceback (most recent call last):
  File "../../trainer.py", line 60, in <module>
    main()
  File "../../trainer.py", line 53, in main
    model = CreateDeepnet(model, train_op, eval_op)
  File "../../trainer.py", line 36, in CreateDeepnet
    return NeuralNet(model, train_op, eval_op)
  File "/home/snail/bash_workspace/1202/deepnet/deepnet/neuralnet.py", line 43, in __init__
    cm.CUDAMatrix.init_random(self.net.seed)
  File "/home/snail/bash_workspace/1202/deepnet/cudamat/cudamat.py", line 224, in init_random
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUDA error: no error

My cuda version is 8.0, do you know how to solve this problem?

Thank you very much!
