### ISSUE TITLE
Stuck at RBM example: ./runall.sh

### ISSUE THREAD

**Issue by UraniumSnake** [nitishsrivastava/deepnet#85]
Hi,
I'm stuck at the RBM example.
When I execute ./runall.sh this is my output:

Traceback (most recent call last):
  File "../../trainer.py", line 1, in <module>
    from neuralnet import *
  File "/home/joaomartinsrei/deepnet/deepnet/neuralnet.py", line 8, in <module>
    from datahandler import *
  File "/home/joaomartinsrei/deepnet/deepnet/datahandler.py", line 4, in <module>
    from choose_matrix_library import *
  File "/home/joaomartinsrei/deepnet/deepnet/choose_matrix_library.py", line 13, in <module>
    from cudamat import cudamat_conv as cc
ImportError: cannot import name cudamat_conv

Already doublecheck ~/.bashrc and nothing seams wrong. Anyone passed by this error?

**Comment by xcszbdnl** [comment]
you should add cudamat to you python search path.
Did you configure PYTHONPATH?

**Comment by Rietaros** [comment]
I have the same problem and I've done adding cudamat to my PYTHONPATH like

export PYTHONPATH=$PYTHONPATH:$HOME/Documents/deepnet-master/cudamat

but still have the same problem. Any idea?

**Comment by guxiaoling** [comment]
I have also encountered the same problem. This problem may be caused by the conflict between two 
cudamat versions. I first install cudamat from https://github.com/cudamat/cudamat. Then during installing deepnet, the cudamat is complied again. I simply delete the first cudamat version by removing python2.7/site-packages/cudamat-0.3-py2.7-linux-x86_64.egg this file folder. It works.
