### ISSUE TITLE
ValueError: array is not broadcastable to correct shape

### ISSUE THREAD

**Issue by eunjilee** [nitishsrivastava/deepnet#86]
In multimodal dbn example, I got the error message like this..

Inferring missing text
Writing to /home/data/flickr/dbn_reps/generated_text/validation
Collecting all representations
Traceback (most recent call last):
  File "collect_dbn_reps.py", line 138, in <module>
    main()
  File "collect_dbn_reps.py", line 82, in main
    data = Merge(data_nnz, data_z, nnz_indices, z_indices, text_pb_z.prefix, text_hidden1_pb.prefix, 'text_hidden1', output_file)
  File "collect_dbn_reps.py", line 125, in Merge
    data[indices_nnz] = data_nnz
ValueError: array is not broadcastable to correct shape

Any idea? Thanks.

**Comment by Qiyu815** [comment]
hi, have you solved this problem ,i have the same promblem
