### ISSUE TITLE
Error while 'make' cudamat

### ISSUE THREAD

**Issue by Rietaros** [nitishsrivastava/deepnet#92]
Hello, I want to start using deepnet (https://github.com/nitishsrivastava/deepnet). For some reason it was built on top of cudamat, so I need to install and i read the tutorial. But I have trouble while i call 'make' file like this:

~/Documents/deepnet-master/cudamat$ sudo make
nvcc -O3 \
-v \
-gencode=arch=compute_10,code=sm_10 \
-gencode=arch=compute_20,code=sm_20 \
-gencode=arch=compute_30,code=sm_30 \
--compiler-options '-fPIC' -o libcudamat.so \
--shared cudamat.cu cudamat_kernels.cu -lcublas -L
nvcc fatal : argument expected after '-L'
make: **\* [libcudamat.so] Error 255

why it happen?
thank you

**Comment by Rietaros** [comment]
Solved.., I forgot to set the environment vari

Now the error become : able

unsupported gpu architecture 'compute_10'

I'm using cuda 7.5.

I need to edit the makefile:

-gencode=arch=compute_10,code=sm_10 \
      -gencode=arch=compute_20,code=sm_20 \
        -gencode=arch=compute_30,code=sm_30 \

what should I type to replace tha compute_10?

**Comment by Rietaros** [comment]
done by editing compute_10 to compute_30 depends on cuda version

And I come up with another problem while running the RBM examples like:

```

Traceback (most recent call last):
  File "../../trainer.py", line 1, in <module>
    from neuralnet import *
  File "/Documents/deepnet-master/deepnet/neuralnet.py", line 8, in <module>
    from datahandler import *
  File "/Documents/deepnet-master/deepnet/datahandler.py", line 4, in <module>e
    from choose_matrix_library import *
  File "/Documents/deepnet-master/deepnet/choose_matrix_library.py", line 13, in <module>
    from cudamat import cudamat_conv as cc
ImportError: cannot import name cudamat_conv
```

I have add the cudamat into my PYTHONPATH
`export PYTHONPATH=$PYTHONPATH:$HOME/Documents/deepnet-master/cudamat`
but still facing the problem.

But when I run:
`import cudamat_conv`
in my python console, nothing wrong 

Any idea?

**Comment by Rietaros** [comment]
Now I just figure it out

in my choose.matrix.library.py line 13, instead of

`from cudamat import cudamat_conv as cc`
  `from cudamat import gpu_lock`

I think it'll work with

`import cudamat_conv as cc`
 `import gpu_lock`

because I've tested it in my python console. But after I edit choose.matrix.library.py, it looks my deepnet doesn't "refresh" the code and still have the same problem output.

Why the code doesn't "resfresh" ?
